#!/usr/bin/env python3
"""Build the GFunnel Methodology Agent Skill.

The skill source lives in skills/gfunnel-methodology/ (SKILL.md + workflows/).
It carries no copy of the canon: inside this repository it reads the repo
itself. This script does two things:

1. Regenerates skills/gfunnel-methodology/SECTIONS.md — a line-numbered index
   of every heading in the canonical version files and the long working
   documents, so an AI can read one section (offset/limit) instead of 300 KB.
   Versions are immutable, so the line numbers stay valid.
2. Builds a portable bundle for places that cannot see the repo (claude.ai,
   the Claude API, another project's .claude/skills/):
       dist/gfunnel-methodology/           SKILL.md, workflows/, SECTIONS.md,
                                           corpus/  <- every tracked repo file
       dist/gfunnel-methodology.zip        the same, zipped with the skill
                                           folder at the zip root

Standard library only (Python 3.8+), same convention as the other tools.

Usage:
  python3 tools/build_skill.py              # regenerate SECTIONS.md, build dist/
  python3 tools/build_skill.py --check      # exit 1 if SECTIONS.md is stale or SKILL.md is malformed
  python3 tools/build_skill.py --index-only # regenerate SECTIONS.md only
  python3 tools/build_skill.py --out DIR    # build the bundle somewhere other than dist/
"""

import argparse
import os
import re
import shutil
import subprocess
import sys
import zipfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SKILL_NAME = "gfunnel-methodology"
SKILL_SRC = os.path.join(ROOT, "skills", SKILL_NAME)
SECTIONS = os.path.join(SKILL_SRC, "SECTIONS.md")
# Claude Code entry point inside the repo: same front matter, body forwards to SKILL_SRC.
CLAUDE_CODE_ENTRY = os.path.join(ROOT, ".claude", "skills", SKILL_NAME, "SKILL.md")

# Files indexed in SECTIONS.md, with the deepest heading level to list.
INDEXED = [
    ("versions/v5.1/GFunnel-Methodology-v5.1.md", 4),
    ("versions/v5.2/GFunnel-Methodology-v5.2.md", 3),
    ("versions/v5.3/GFunnel-Methodology-v5.3.md", 3),
    ("versions/v5.4/GFunnel-Methodology-v5.4.md", 3),
    ("tasks/reality-audit/TASK.md", 2),
    ("audit/SCHEMA.md", 2),
    ("framework/registers.md", 2),
]

# Never copied into corpus/: the skill itself (it is the bundle root), agent
# config, and build output.
CORPUS_EXCLUDE_PREFIXES = ("skills/", ".claude/", "dist/")

HEADING_RE = re.compile(r"^(#{1,6})\s+(.*?)\s*#*\s*$")
APPENDIX_RE = re.compile(r"^>\s*(APPENDIX [A-Z])\s*$")
FENCE_RE = re.compile(r"^(```|~~~)")

NAME_RE = re.compile(r"^[a-z0-9]+(-[a-z0-9]+)*$")


def rel(path):
    return os.path.relpath(path, ROOT).replace(os.sep, "/")


def read_lines(path):
    with open(path, encoding="utf-8") as fh:
        return fh.read().splitlines()


def headings(lines, max_level):
    """Return [(line_no, level, title)] for markdown headings and appendix markers."""
    out = []
    in_fence = False
    for i, line in enumerate(lines, start=1):
        if FENCE_RE.match(line):
            in_fence = not in_fence
            continue
        if in_fence:
            continue
        m = HEADING_RE.match(line)
        if m and len(m.group(1)) <= max_level:
            out.append((i, len(m.group(1)), m.group(2)))
            continue
        a = APPENDIX_RE.match(line)
        if a:
            # v5.1 marks appendices with a blockquote; the title is in its contents table.
            out.append((i, 2, a.group(1)))
    return out


def section_rows(lines, max_level):
    """Each heading with the line range it spans (until the next heading of equal or higher rank)."""
    hs = headings(lines, max_level)
    rows = []
    for idx, (start, level, title) in enumerate(hs):
        end = len(lines)
        for nstart, nlevel, _ in hs[idx + 1:]:
            if nlevel <= level:
                end = nstart - 1
                break
        rows.append((start, end, level, title))
    return rows


def render_index():
    parts = [
        "# SECTIONS — Line-Numbered Index of the Corpus",
        "",
        "> Generated by `tools/build_skill.py` — do not edit by hand. Run `python3 tools/build_skill.py --index-only` after any canonical change.",
        "",
        "Read one section instead of a whole file: open the path (relative to the corpus root, see `SKILL.md`) at `offset = start`, `limit = end - start + 1`.",
        "Ranges are inclusive and nest: a `###` range sits inside its `##` range. Released versions are immutable, so these numbers do not drift.",
        "",
    ]
    for path, max_level in INDEXED:
        full = os.path.join(ROOT, path)
        if not os.path.exists(full):
            continue
        lines = read_lines(full)
        parts.append("## `%s` (%d lines)" % (path, len(lines)))
        parts.append("")
        parts.append("| Lines | Section |")
        parts.append("| --- | --- |")
        for start, end, level, title in section_rows(lines, max_level):
            if level == 1:
                continue
            indent = "&nbsp;&nbsp;" * max(0, level - 2)
            title = title.replace("|", "\\|")
            parts.append("| %d–%d | %s%s |" % (start, end, indent, title))
        parts.append("")
    return "\n".join(parts).rstrip() + "\n"


def front_matter(path):
    lines = read_lines(path)
    if not lines or lines[0].strip() != "---" or "---" not in lines[1:]:
        return None
    return lines[: lines[1:].index("---") + 2]


def check_skill_md():
    """Return a list of errors in SKILL.md front matter."""
    errors = []
    path = os.path.join(SKILL_SRC, "SKILL.md")
    lines = read_lines(path)
    if not lines or lines[0].strip() != "---":
        return ["SKILL.md: must start with '---' front matter"]
    try:
        end = lines[1:].index("---") + 1
    except ValueError:
        return ["SKILL.md: front matter is not closed with '---'"]
    fields = {}
    for line in lines[1:end]:
        if ":" in line and not line.startswith(" "):
            key, _, value = line.partition(":")
            fields[key.strip()] = value.strip()
    name = fields.get("name", "")
    desc = fields.get("description", "")
    if name != SKILL_NAME:
        errors.append("SKILL.md: name must be %r (the folder name), got %r" % (SKILL_NAME, name))
    if not NAME_RE.match(name) or len(name) > 64:
        errors.append("SKILL.md: name must be lowercase letters, digits and hyphens, at most 64 chars")
    if not desc:
        errors.append("SKILL.md: description is required")
    elif len(desc) > 1024:
        errors.append("SKILL.md: description is %d chars; the limit is 1024" % len(desc))
    if "<" in desc or ">" in desc:
        errors.append("SKILL.md: description must not contain angle brackets")
    body = len(lines) - end - 1
    if body > 500:
        errors.append("SKILL.md: body is %d lines; keep it under 500 and move detail to workflows/" % body)
    # Every workflow / file the router names must exist.
    text = "\n".join(lines)
    for ref in sorted(set(re.findall(r"`(workflows/[a-z0-9-]+\.md)`", text))):
        if not os.path.exists(os.path.join(SKILL_SRC, ref)):
            errors.append("SKILL.md: references missing file %s" % ref)
    errors.extend(check_paths())
    if os.path.exists(CLAUDE_CODE_ENTRY) and front_matter(CLAUDE_CODE_ENTRY) != front_matter(path):
        errors.append("%s: front matter must match %s exactly" % (rel(CLAUDE_CODE_ENTRY), rel(path)))
    return errors


PATH_RE = re.compile(r"`([A-Za-z0-9_.][A-Za-z0-9_./-]*(?:/|\.(?:md|py|yml|txt|cff)))`")


def check_paths():
    """Every repo path the skill names in backticks must exist (skill dir or corpus root)."""
    errors = []
    for dirpath, _, filenames in os.walk(SKILL_SRC):
        for fn in filenames:
            if not fn.endswith(".md") or fn == "SECTIONS.md":
                continue
            src = os.path.join(dirpath, fn)
            for ref in sorted(set(PATH_RE.findall(open(src, encoding="utf-8").read()))):
                # Bare file names are prose; paths still to be created (a future version draft) are not checked.
                if "/" not in ref or "<" in ref or "X.Y" in ref or "v5.5" in ref or ref.startswith("corpus/"):
                    continue
                if not any(os.path.exists(os.path.join(base, ref)) for base in (SKILL_SRC, ROOT)):
                    errors.append("%s: names missing path %s" % (rel(src), ref))
    return errors


def tracked_files():
    try:
        out = subprocess.run(
            ["git", "ls-files", "-z", "--cached", "--others", "--exclude-standard"], cwd=ROOT, check=True, capture_output=True
        ).stdout.decode("utf-8")
        files = [f for f in out.split("\0") if f]
    except (OSError, subprocess.CalledProcessError):
        files = []
        for dirpath, dirnames, filenames in os.walk(ROOT):
            dirnames[:] = [d for d in dirnames if d not in (".git", "__pycache__")]
            for fn in filenames:
                files.append(rel(os.path.join(dirpath, fn)))
    return sorted(
        f for f in files
        if not f.startswith(CORPUS_EXCLUDE_PREFIXES) and "__pycache__" not in f
        and os.path.isfile(os.path.join(ROOT, f))
    )


def build(out_dir):
    target = os.path.join(out_dir, SKILL_NAME)
    if os.path.exists(target):
        shutil.rmtree(target)
    shutil.copytree(SKILL_SRC, target, ignore=shutil.ignore_patterns("__pycache__"))
    corpus = os.path.join(target, "corpus")
    files = tracked_files()
    for f in files:
        dest = os.path.join(corpus, f)
        os.makedirs(os.path.dirname(dest), exist_ok=True)
        shutil.copy2(os.path.join(ROOT, f), dest)

    zip_path = os.path.join(out_dir, SKILL_NAME + ".zip")
    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
        for dirpath, _, filenames in os.walk(target):
            for fn in sorted(filenames):
                full = os.path.join(dirpath, fn)
                zf.write(full, os.path.relpath(full, out_dir).replace(os.sep, "/"))
    size = os.path.getsize(zip_path)
    print("built %s (%d corpus files)" % (rel(target) if target.startswith(ROOT) else target, len(files)))
    print("built %s (%.0f KB)" % (rel(zip_path) if zip_path.startswith(ROOT) else zip_path, size / 1024))


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="verify SECTIONS.md is current and SKILL.md is valid; write nothing")
    ap.add_argument("--index-only", action="store_true", help="regenerate SECTIONS.md and stop")
    ap.add_argument("--out", default=os.path.join(ROOT, "dist"), help="bundle output directory (default: dist/)")
    args = ap.parse_args()

    errors = check_skill_md()
    index = render_index()
    if args.check:
        current = open(SECTIONS, encoding="utf-8").read() if os.path.exists(SECTIONS) else ""
        if current != index:
            errors.append("SECTIONS.md is stale: run python3 tools/build_skill.py --index-only")
        for e in errors:
            print("ERROR " + e)
        print("ok" if not errors else "%d error(s)" % len(errors))
        return 1 if errors else 0

    for e in errors:
        print("ERROR " + e)
    if errors:
        return 1
    with open(SECTIONS, "w", encoding="utf-8") as fh:
        fh.write(index)
    print("wrote %s" % rel(SECTIONS))
    if not args.index_only:
        build(os.path.abspath(args.out))
    return 0


if __name__ == "__main__":
    sys.exit(main())
